namespace: healthify

imagePullSecrets: []

frontend:
  image:
    repository: "124502390077.dkr.ecr.ap-south-1.amazonaws.com/healthify-frontend"
    tag: "v4"
    pullPolicy: IfNotPresent

  replicas: 2

  service:
    port: 80

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi


gateway:
  image:
    repository: "124502390077.dkr.ecr.ap-south-1.amazonaws.com/healthify-gateway"
    tag: "v3"
    pullPolicy: IfNotPresent

  replicas: 2

  service:
    port: 80

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi


auth:
  image:
    repository: "124502390077.dkr.ecr.ap-south-1.amazonaws.com/healthify-auth"
    tag: "v1"
    pullPolicy: IfNotPresent

  replicas: 2

  service:
    port: 8000

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi


report:
  image:
    repository: "124502390077.dkr.ecr.ap-south-1.amazonaws.com/healthify-report"
    tag: "v2"
    pullPolicy: IfNotPresent

  replicas: 2

  service:
    port: 8001

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi


ai:
  image:
    repository: "124502390077.dkr.ecr.ap-south-1.amazonaws.com/healthify-ai"
    tag: "v2"
    pullPolicy: IfNotPresent

  replicas: 1

  service:
    port: 8002

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi


ollama:
  image:
    repository: "ollama/ollama"
    tag: "latest"
    pullPolicy: IfNotPresent

  replicas: 1

  service:
    port: 11434

  storage:
    size: 20Gi
    storageClass: gp3

  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi


database:
  host: ""
  port: 5432
  name: healthai


s3:
  bucket: "weareavengeres"
  region: ap-south-1


secrets:
  create: false
  existingSecret: healthify-secrets


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70


podDisruptionBudget:
  enabled: true
  minAvailable: 1