apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: healthify
  namespace: argocd

spec:
  project: healthify

  source:
    repoURL: https://github.com/KaleeswarG25/healthify_AI.git
    targetRevision: master
    path: infrastructure/kubernetes/helm

    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: healthify

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true