apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aihealth
  namespace: argocd
  labels:
    app: aihealth
spec:
  project: default
  source:
    repoURL: https://github.com/KaleeswarG25/healthify_AI.git
    path: k8s-live
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: aihealth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
