apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3

  resources:
    requests:
      storage: 20Gi