{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecret }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
{{- end }}