apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthify-auth
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: healthify
    app.kubernetes.io/component: auth
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthify-report
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: healthify
    app.kubernetes.io/component: report
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthify-ai
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: healthify
    app.kubernetes.io/component: ai
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthify-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: healthify
    app.kubernetes.io/component: gateway
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthify-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: healthify
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthify-ollama
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: healthify
    app.kubernetes.io/component: ollama
automountServiceAccountToken: false