apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: {{ .Values.namespace }}
  labels:
    app: report-service
spec:
  type: ClusterIP
  selector:
    app: report-service
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: {{ .Values.namespace }}
  labels:
    app: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.namespace }}
  labels:
    app: ollama
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - name: http
      port: 11434
      targetPort: http
      protocol: TCP